sudo: required

language: c

compiler: gcc

before_script:
  - sudo sysctl -w vm.nr_hugepages=512

script:
 - make -j
 - (cd src && sudo program/vita/selftest.snabb)
 - (cd src && sudo ./snabb snsh -t program.vita.exchange)
 - (cd src && sudo program/vita/conftest.snabb)
 - (cd src && sudo program/vita/test.snabb IMIX 1e6 3)
 - (cd src && sudo program/vita/test6.snabb IMIX 1e6 3)
